# Generated by Django 5.0.6 on 2024-05-09 09:54

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_Shop', '0003_images_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter_price',
            name='price',
            field=models.CharField(choices=[('0 TO 200', '0 TO 200'), ('200 TO 500', '200 TO 500'), ('500 TO 1000', '500 TO 1000'), ('1000 TO 2000', '1000 TO 2000'), ('2000+', '2000+')], max_length=60),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='information',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
