# Generated by Django 5.0.6 on 2024-05-10 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_Shop', '0006_order_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='amout',
            new_name='amount',
        ),
        migrations.AddField(
            model_name='order',
            name='paid',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_id',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
