# Generated by Django 5.0.4 on 2024-05-11 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('E_Shop', '0007_rename_amout_order_amount_order_paid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='county',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='fistname',
            new_name='firstname',
        ),
        migrations.RemoveField(
            model_name='order',
            name='additional_info',
        ),
    ]
