# Generated by Django 5.0.4 on 2024-05-12 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_Shop', '0008_rename_county_order_country_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categoires',
            new_name='Categorie',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='product_image',
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Product_images/img')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='E_Shop.product')),
            ],
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
